export const mockData = [
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c501",
        id: 1,
        nome: "Tipo 1",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c502",
        id: 2,
        nome: "Tipo 2",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c503",
        id: 3,
        nome: "Tipo 3",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c504",
        id: 4,
        nome: "Tipo 4",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c505",
        id: 5,
        nome: "Tipo 5",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c506",
        id: 6,
        nome: "Tipo 6",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c507",
        id: 7,
        nome: "Tipo 7",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c508",
        id: 8,
        nome: "Tipo 8",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c509",
        id: 9,
        nome: "Tipo 9",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c510",
        id: 10,
        nome: "Tipo 10",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c511",
        id: 11,
        nome: "Tipo 11",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c512",
        id: 12,
        nome: "Tipo 12",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c513",
        id: 13,
        nome: "Tipo 13",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c514",
        id: 14,
        nome: "Tipo 14",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c515",
        id: 15,
        nome: "Tipo 15",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c516",
        id: 16,
        nome: "Tipo 16",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c517",
        id: 17,
        nome: "Tipo 17",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c518",
        id: 18,
        nome: "Tipo 18",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c519",
        id: 19,
        nome: "Tipo 19",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c520",
        id: 20,
        nome: "Tipo 20",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
    {
        uuid: "ba8b96ef-f05c-41f3-af10-73753490c521",
        id: 21,
        nome: "Tipo 21",
        apenas_digitos: false,
        numero_documento_digitado: false,
        pode_reter_imposto: false,
        eh_documento_de_retencao_de_imposto: false,
        documento_comprobatorio_de_despesa: false,
    },
];

export const mockEdit = {
    nome: "Nome do tipo",
    numero_documento_digitado: null,
    apenas_digitos: null,
    documento_comprobatorio_de_despesa: null,
    pode_reter_imposto: null,
    eh_documento_de_retencao_de_imposto: null,
    id: 1,
    uuid: "12345",
    operacao: "edit"
};

export const mockCreate = {
    nome: "",
    numero_documento_digitado: false,
    apenas_digitos: false,
    documento_comprobatorio_de_despesa: false,
    pode_reter_imposto: false,
    eh_documento_de_retencao_de_imposto: false,
    id: null,
    uuid: null,
    operacao: 'create'
};