export const STATUS_CONTA_ASSOCIACAO = {
  ATIVA: "ATIVA",
  INATIVA: "INATIVA",
};

export const STATUS_SOLICITACAO_ENCERRAMENTO_CONTA_ASSOCIACAO = {
  PENDENTE: "PENDENTE",
  REJEITADA: "REJEITADA",
  APROVADA: "APROVADA",
};
