export const mockTabelaDespesas = {
  tipos_aplicacao_recurso: [
    {
      id: "CAPITAL",
      nome: "Capital",
    },
    {
      id: "CUSTEIO",
      nome: "Custeio",
    },
  ],
  tipos_custeio: [
    {
      nome: "Banco do Brasil - Alterar2",
      id: 2,
      uuid: "250f0e3b-c5c5-4a8c-95e4-c31e55e30574",
      eh_tributos_e_tarifas: false,
    },
    {
      nome: "Gênero alimentício",
      id: 5,
      uuid: "14d11302-226e-4f8c-9fc4-be6a48ec0728",
      eh_tributos_e_tarifas: false,
    },
    {
      nome: "Imposto",
      id: 4,
      uuid: "e7e9e35f-4ba2-4806-b9b8-13c7f3bc9a5f",
      eh_tributos_e_tarifas: true,
    },
    {
      nome: "Material",
      id: 1,
      uuid: "30afe42e-baea-4d70-b54d-bbc41508f720",
      eh_tributos_e_tarifas: false,
    },
    {
      nome: "Mobiliário",
      id: 6,
      uuid: "1667e023-ca30-4c30-8002-219cc9338577",
      eh_tributos_e_tarifas: false,
    },
    {
      nome: "Serviço",
      id: 3,
      uuid: "fc224e09-9ffb-44dc-add8-17a79e969dd9",
      eh_tributos_e_tarifas: false,
    },
    {
      nome: "teste1",
      id: 8,
      uuid: "bdedc8b9-584a-4e28-95b7-2e50a189c5b0",
      eh_tributos_e_tarifas: false,
    },
    {
      nome: "Tributos",
      id: 7,
      uuid: "7da9b355-8ab9-4171-8382-746652fd62cc",
      eh_tributos_e_tarifas: false,
    },
  ],
  tipos_documento: [
    {
      uuid: "e059ca78-d6d9-4f9e-8ffa-4fdc5e3f714a",
      id: 9,
      nome: "Comprovante",
      apenas_digitos: false,
      numero_documento_digitado: true,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: true,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "9249902c-f58f-477b-a5af-c3ed412a387a",
      id: 1,
      nome: "Cupom fiscal",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "a99e7392-e759-470c-8d34-110073d79c0f",
      id: 10,
      nome: "DAMSP",
      apenas_digitos: false,
      numero_documento_digitado: false,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: true,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "aeaa9c0b-f785-4101-9675-c7f5e0ad3cb1",
      id: 2,
      nome: "DANFE",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "3e9f609a-012b-4835-a651-e035dbf84baa",
      id: 11,
      nome: "DARF",
      apenas_digitos: false,
      numero_documento_digitado: false,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: true,
      documento_comprobatorio_de_despesa: false,
    },
    {
      uuid: "3fcce4e3-a7b2-4c12-99d6-b4313fb8c273",
      id: 12,
      nome: "DARF Previdenciário",
      apenas_digitos: false,
      numero_documento_digitado: false,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: true,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "404a3252-43e8-4f3c-adac-056d2905b18d",
      id: 3,
      nome: "Extrato",
      apenas_digitos: false,
      numero_documento_digitado: false,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "c19c17c6-448e-4fe9-a4cc-975d84b3e864",
      id: 8,
      nome: "Fatura",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "d094899d-4d87-4661-98d5-f0b20868faf9",
      id: 4,
      nome: "Guia de recolhimento",
      apenas_digitos: false,
      numero_documento_digitado: false,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "4b89e2ab-da20-4907-a48d-4121a338a13a",
      id: 5,
      nome: "NF",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "351cb237-fa53-42df-9a26-7905a1869d51",
      id: 6,
      nome: "NFS-e",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: true,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "147bbabd-234f-4438-8cf2-218f875a60c5",
      id: 13,
      nome: "Prenota",
      apenas_digitos: false,
      numero_documento_digitado: false,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "f4cb939b-d354-417a-b046-91977ebeebe4",
      id: 7,
      nome: "Recibo",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: false,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "3f7ec071-c747-41ba-9d23-bb8e70a4cb80",
      id: 46,
      nome: "SME Teste",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: true,
      eh_documento_de_retencao_de_imposto: false,
      documento_comprobatorio_de_despesa: true,
    },
    {
      uuid: "af65f4d9-7594-43bc-8352-733d96b09204",
      id: 44,
      nome: "teste12343",
      apenas_digitos: true,
      numero_documento_digitado: true,
      pode_reter_imposto: true,
      eh_documento_de_retencao_de_imposto: true,
      documento_comprobatorio_de_despesa: true,
    },
  ],
  tipos_transacao: [
    {
      id: 3,
      nome: "Cartão",
      tem_documento: true,
    },
    {
      id: 1,
      nome: "Cheque",
      tem_documento: true,
    },
    {
      id: 8,
      nome: "Débito em conta",
      tem_documento: false,
    },
    {
      id: 4,
      nome: "DOC/TED/PIX",
      tem_documento: false,
    },
    {
      id: 28,
      nome: "Documento rayanne",
      tem_documento: true,
    },
    {
      id: 7,
      nome: "Pagamento via aplicativo/ASP/TAA",
      tem_documento: false,
    },
    {
      id: 6,
      nome: "Saque com cartão",
      tem_documento: false,
    },
    {
      id: 2,
      nome: "Saque com cheque",
      tem_documento: true,
    },
    {
      id: 34,
      nome: "Sme teste",
      tem_documento: true,
    },
    {
      id: 22,
      nome: "teste 9",
      tem_documento: false,
    },
    {
      id: 32,
      nome: "Teste review 123",
      tem_documento: false,
    },
    {
      id: 5,
      nome: "Transferência entre contas BB",
      tem_documento: false,
    },
  ],
  acoes_associacao: [
    {
      uuid: "3dcf3205-30e2-4a9f-83e7-52cdb1a07465",
      id: 962,
      nome: "PTRF Básico",
      e_recursos_proprios: false,
      acao: {
        id: 3,
        uuid: "bdcbc8ce-7bab-48b3-959a-f866c6644579",
        nome: "PTRF Básico",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "AAAAAAAAAA",
        aceita_capital: true,
        aceita_custeio: true,
        aceita_livre: true,
      },
    },
    {
      uuid: "ae2927ef-e904-497e-b8a8-352bd8fae62c",
      id: 2799,
      nome: "Salas e Espaços de Leitura",
      e_recursos_proprios: false,
      acao: {
        id: 14,
        uuid: "d04e1b77-2db4-482a-86b7-04a788935ffe",
        nome: "Salas e Espaços de Leitura",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "JJJJJJJJJJ",
        aceita_capital: false,
        aceita_custeio: false,
        aceita_livre: true,
      },
    },
    {
      uuid: "9ec04922-8cf1-42dc-9871-87cc9cebdc7b",
      id: 4207,
      nome: "Material Pedagógico",
      e_recursos_proprios: false,
      acao: {
        id: 15,
        uuid: "4e56e1f9-f2d0-4a05-84b1-2a7a449f73c3",
        nome: "Material Pedagógico",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "IIIIIIIIII",
        aceita_capital: false,
        aceita_custeio: true,
        aceita_livre: false,
      },
    },
    {
      uuid: "f7392c94-3a8d-4b88-b989-a1019802b905",
      id: 6258,
      nome: "Formação",
      e_recursos_proprios: false,
      acao: {
        id: 8,
        uuid: "b80996f8-2e58-4764-afe2-5d58e50ed364",
        nome: "Formação",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "GGGGGGGGGG",
        aceita_capital: false,
        aceita_custeio: true,
        aceita_livre: false,
      },
    },
    {
      uuid: "b3b56321-e78a-46de-beb3-4d08a835a518",
      id: 8169,
      nome: "Recurso Externo",
      e_recursos_proprios: true,
      acao: {
        id: 13,
        uuid: "d266beb2-903a-4b4f-ae6e-c2eec185aa6b",
        nome: "Recurso Externo",
        e_recursos_proprios: true,
        posicao_nas_pesquisas: "ZZZZZZZZZZ",
        aceita_capital: true,
        aceita_custeio: true,
        aceita_livre: true,
      },
    },
    {
      uuid: "182fdbfb-4f66-4c05-a205-077683525d50",
      id: 10043,
      nome: "Rolê Cultural",
      e_recursos_proprios: false,
      acao: {
        id: 12,
        uuid: "e47b636b-3d28-45d3-a4fb-09427202aa80",
        nome: "Rolê Cultural",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "DDDDDDDDDD",
        aceita_capital: false,
        aceita_custeio: true,
        aceita_livre: false,
      },
    },
    {
      uuid: "2beadbca-fc88-43be-8b76-4bbd0540c5e4",
      id: 10875,
      nome: "Fazendo Futuro",
      e_recursos_proprios: false,
      acao: {
        id: 4,
        uuid: "920e1373-7b6f-46ec-a7e3-9e47d5751be7",
        nome: "Fazendo Futuro",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "CCCCCCCCCC",
        aceita_capital: false,
        aceita_custeio: true,
        aceita_livre: false,
      },
    },
    {
      uuid: "c11a415d-9c70-43e6-bff2-61ee5e752993",
      id: 12847,
      nome: "Orçamento Grêmio Estudantil",
      e_recursos_proprios: false,
      acao: {
        id: 2,
        uuid: "1abb18d7-481f-4fae-8758-ec4e3a1bd523",
        nome: "Orçamento Grêmio Estudantil",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "EEEEEEEEEE",
        aceita_capital: true,
        aceita_custeio: true,
        aceita_livre: true,
      },
    },
    {
      uuid: "863899cc-c4a1-479e-8113-606a3576daae",
      id: 12970,
      nome: "Programa de Cuidados com as Estudantes",
      e_recursos_proprios: false,
      acao: {
        id: 16,
        uuid: "882801b1-461d-42f2-bb2a-e4b691d15bea",
        nome: "Programa de Cuidados com as Estudantes",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "LLLLLLLLLL",
        aceita_capital: false,
        aceita_custeio: true,
        aceita_livre: false,
      },
    },
    {
      uuid: "1240d3a5-c5bb-4385-bfb5-7d3d7568fe31",
      id: 13494,
      nome: "Material Complementar",
      e_recursos_proprios: false,
      acao: {
        id: 17,
        uuid: "8006c807-d113-4c41-8337-64fb2f0f7931",
        nome: "Material Complementar",
        e_recursos_proprios: false,
        posicao_nas_pesquisas: "NNNNNNNNNN",
        aceita_capital: false,
        aceita_custeio: true,
        aceita_livre: false,
      },
    },
  ],
  contas_associacao: [
    {
      uuid: "0e02f4d9-b0f8-4025-8d1a-5aad85002e5d",
      nome: "C6 BANK",
      status: "INATIVA",
      solicitacao_encerramento: null,
      data_inicio: "2024-06-16",
    },
    {
      uuid: "166770b1-7325-486f-a588-c8da3cf56a68",
      nome: "Cartão",
      status: "INATIVA",
      solicitacao_encerramento: {
        uuid: "e72736c3-bc92-40a5-8052-4b63b96bae0a",
        conta_associacao: "166770b1-7325-486f-a588-c8da3cf56a68",
        status: "APROVADA",
        data_de_encerramento_na_agencia: "2025-07-16",
        motivos_rejeicao: [
          {
            uuid: "b683b964-0809-4fc1-931c-d58bf7c202a6",
            nome: "Falta de documento comprobatório",
            criado_em: "2023-10-02T17:17:53.348671",
            id: 1,
          },
        ],
        outros_motivos_rejeicao: "",
        data_aprovacao: "2025-07-16",
        criado_em: "2025-07-16T09:47:46.500822",
        alterado_em: "2025-07-16T09:47:46.500835",
        msg_sucesso_ao_encerrar:
          "Existem valores reprogramados que não foram preenchidos pela DRE. É necessário aguardar a finalização do preenchimento para solicitar o encerramento da conta bancária.",
      },
      data_inicio: "2022-09-01",
    },
    {
      uuid: "d7cf7c03-bc2f-427f-a35f-62076fab0e1b",
      nome: "Cheque",
      status: "ATIVA",
      solicitacao_encerramento: null,
      data_inicio: "2022-09-01",
    },
  ],
  tags: [
    {
      uuid: "569b6e74-a042-4ee0-a671-b1e96a34e363",
      nome: "Teste etiqueta/tag",
      status: "ATIVO",
      id: 4,
    },
  ],
};

export const mockTransasoes = [
  {
    periodo: "022e2d4c-7b66-45e9-980b-fc9283e825ad",
    conta: "d7cf7c03-bc2f-427f-a35f-62076fab0e1b",
    data: "2023-04-25",
    tipo_transacao: "Gasto",
    numero_documento: "",
    descricao: "BANCO DO BRASIL S/A",
    valor_transacao_total: 60.5,
    valor_transacao_na_conta: 60.5,
    valores_por_conta: [
      {
        conta_associacao__tipo_conta__nome: "Cheque",
        valor_rateio__sum: 60.5,
      },
    ],
    conferido: true,
    informacoes: [
      {
        tag_id: "9",
        tag_nome: "Conciliada",
        tag_hint: "Essa despesa já possui conciliação bancária.",
      },
    ],
    documento_mestre: {
      associacao: "e7837d4a-9227-4f71-ae69-922549d7bb1c",
      numero_documento: "",
      tipo_documento: {
        id: 3,
        nome: "Extrato",
      },
      tipo_transacao: {
        id: 8,
        nome: "Cheque",
        tem_documento: false,
      },
      documento_transacao: "",
      data_documento: "2023-04-25",
      data_transacao: "2023-04-25",
      cpf_cnpj_fornecedor: "00.000.000/0001-91",
      nome_fornecedor: "BANCO DO BRASIL S/A",
      valor_ptrf: 60.5,
      valor_total: "60.50",
      status: "COMPLETO",
      conferido: true,
      uuid: "0ad961bf-0b03-4f5a-b68a-fe45bf6762e9",
    },
    rateios: [
      {
        uuid: "38dc8f30-f95f-4b25-8b7e-48023ee314c9",
        especificacao_material_servico: {
          id: 6295,
          uuid: "c2dd3ffb-e38f-4c77-9bc3-b526a73f7d44",
          descricao: "Tarifa bancária: renovação de cadastro",
          aplicacao_recurso: "CUSTEIO",
          tipo_custeio: 2,
          ativa: true,
        },
        aplicacao_recurso: "CUSTEIO",
        acao_associacao: {
          uuid: "3dcf3205-30e2-4a9f-83e7-52cdb1a07465",
          id: 962,
          nome: "PTRF Básico",
          e_recursos_proprios: false,
          acao: {
            id: 3,
            uuid: "bdcbc8ce-7bab-48b3-959a-f866c6644579",
            nome: "PTRF Básico",
            e_recursos_proprios: false,
            posicao_nas_pesquisas: "AAAAAAAAAA",
            aceita_capital: true,
            aceita_custeio: true,
            aceita_livre: true,
          },
        },
        valor_rateio: "60.50",
        conferido: true,
        notificar_dias_nao_conferido: 0,
        tipo_custeio: {
          nome: "Banco do Brasil - Alterar2",
          id: 2,
          uuid: "250f0e3b-c5c5-4a8c-95e4-c31e55e30574",
          eh_tributos_e_tarifas: false,
        },
        tag: null,
        estorno: {
          data: null,
          valor: null,
          tipo_receita: {
            nome: "",
            e_repasse: false,
            aceita_capital: false,
            aceita_custeio: false,
            aceita_livre: false,
            e_devolucao: false,
            e_recursos_proprios: false,
          },
          categoria_receita: null,
          detalhe_tipo_receita: null,
          detalhe_outros: "",
        },
      },
    ],
    notificar_dias_nao_conferido: 0,
    despesa_geradora_do_imposto: null,
    despesas_impostos: null,
  },
];

export const mockTransasoesDebito = [
  {
    ...mockTransasoes[0],
    documento_mestre: {
      ...mockTransasoes[0].documento_mestre,
      tipo_transacao: {
        id: 8,
        nome: "Débito",
        tem_documento: false,
      },
    },
  },
];

export const mockTransasoesCredito = [
  {
    ...mockTransasoes[0],
    tipo_transacao: "Crédito",
    notificar_dias_nao_conferido: 1,
  },
];
